### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
adapter_name_or_path: /media/volume/Replication/ad-doc-reranker/sft_output
reward_model: saves/llama3-8b/lora/reward
trust_remote_code: true

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
gradient_checkpointing: true

### dataset
dataset: train_ppo
template: llama3
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 12
dataloader_num_workers: 12

### output
output_dir: saves/llama3-8b/lora/ppo
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9

### deepspeed
deepspeed:
  train_micro_batch_size_per_gpu: 4
  gradient_accumulation_steps: 4
  zero_stage: 2
  offload_optimizer:
    device: "cpu"
    pin_memory: true
  offload_param:
    device: "none"
  zero3_init_flag: false
  zero_optimization:
    stage: 2
    allgather_partitions: true
    allgather_bucket_size: 500000000
    overlap_comm: true
    reduce_scatter: true
    reduce_bucket_size: 500000000
    contiguous_gradients: true
